apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : the-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: bs-app
  source:
    path   : "HelmCharts/MyChart"
    repoURL: "https://github.com/thearmanv/argocd.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true